<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net7.0-android;net6.0-android;</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjoxam.BillingClient.Droid</PackageId>
		<PackageVersion>6.0.0</PackageVersion>
		<AssemblyVersion>6.0.0</AssemblyVersion>
		<FileVersion>6.0.0</FileVersion>
		<Version>6.0.0</Version>
		<Title>Anjo Billing Client Droid</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjoxam.BillingClient.Droid</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) Binding Library - Billing Client</Description>
		<PackageReleaseNotes>Billing Client v6.0.0</PackageReleaseNotes>
		<Copyright>Copyright (c) 2023 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, Billing Client, Google Play Billing , In-AppBilling, In-App Purchases</PackageTags>
		<Summary>Google Play's billing system is a service that enables you to sell digital products and content in your Android app.</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="Jars\billing-6.0.0.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Xamarin.Google.Android.DataTransport.TransportApi" Version="3.0.0.6" />
	  <PackageReference Include="Xamarin.Google.Android.DataTransport.TransportBackendCct" Version="3.1.9" />
	  <PackageReference Include="Xamarin.Google.Android.DataTransport.TransportRuntime" Version="3.1.9" />
	</ItemGroup>
</Project>